load("@io_bazel_rules_go//go/tools/bazel_testing:def.bzl", "go_bazel_test")

go_bazel_test(
    name = "watch_local_files_listed_after_external_files_test",
    srcs = ["watch_local_files_listed_after_external_files_test.go"],
    deps = ["//internal/e2e"],
)
